version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yii2-app
    ports:
      - "8337:80"
    volumes:
      - ./runtime:/var/www/html/runtime
      - ./web/assets:/var/www/html/web/assets
    command: >
      bash -c "
      mkdir -p /var/www/html/runtime /var/www/html/web/assets &&
      chown -R www-data:www-data /var/www/html/runtime /var/www/html/web/assets &&
      chmod -R 775 /var/www/html/runtime /var/www/html/web/assets &&
      apache2-foreground
      "
    environment:
      - MONGODB_STRING=mongodb://mongodb:27017/test_db123
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "21337:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local